myapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('request/', include('request.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/request/'))
]

request/urls.py
from django.urls import path
from .import views

app_name = 'request'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail')
]

request/models.py
from django.db import models

# Create your models here.

request/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .weatherari import fetch_weather

def index(request):
    return render(request, 'request/index.html')

def detail(request):
    place = request.POST["place"]
        
    weather_deta = fetch_weather(place)
    context = {
        "weather_deta": weather_deta,
    }


    return render(request, 'request/detail.html', context)

request/templates/request/detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>地域別天気予報</title>
</head>
<body>
    <h1>Weather Information</h1>
    <h2>{{weather_deta.prefecture}} {{weather_deta.date}}の天気</h2>
    <div>{{weather_deta.image|safe}}</div>
    <h3>{{weather_deta.weather}}</h3>
    <p>最高気温：{{weather_deta.max}}</p>
    <p>最低気温：{{weather_deta.min}}</p>
    <a href='{% url "request:index" %}'>トップページに戻る</a>
</body>
</html>

request/templates/request/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>お天気サイト練習用</title>
</head>
<body>
    <h1>Weather Information</h1>
    <h2>今日の天気を知りたい場所を選択してください。</h2>

    <form action="{% url 'request:detail' %}" method="post">
        {% csrf_token %}
        <select name="place" required>
            <option value="270000">大阪</option>
            <option value="280010">兵庫（神戸）</option>
            <option value="290010">奈良</option>
            <option value="300010">和歌山</option>
            <option value="260010">京都</option>
            <option value="250010">滋賀（大津）</option>
            <option value="240010">三重（津）</option>
        </select>
        <button type="submit">確認する</button>
    </form>
</body>
</html>